[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_SITE_URL = "https://planidocs.com"

# Redirections pour SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Configuration des en-têtes (les headers spécifiques sont dans _headers)
[[headers]]
  for = "/*"
  [headers.values]
    # Headers de base sont dans _headers, ici on ajoute juste les extras
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Optimisations de performance
[build.processing]
  skip_processing = false

[build.processing.css]
  minify = true

[build.processing.js]
  minify = true

[build.processing.html]
  pretty_urls = false

[build.processing.images]
  compress = true

# Plugins pour optimisations supplémentaires
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

# Cache des assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"